services:
  db:
    image: mariadb:latest
    container_name: ${ROUTER}-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  gestio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${ROUTER}-app
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}

      - LDAP_URL=ldap://ldap-server:389
      - LDAP_BASE_DN=${LDAP_BASE_DN}
      - LDAP_BIND_DN=${LDAP_BIND_DN}
      - LDAP_BIND_PW=${LDAP_BIND_PW}
      - LDAP_USER_SEARCH=${LDAP_USER_SEARCH}

      - AUTH_SECRET=${AUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_URL_INTERNAL=${NEXTAUTH_URL_INTERNAL}
    depends_on:
      - db
    networks:
      - app-network
      - webnet-ldap

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: ${ROUTER}-phpmyadmin
    restart: always
    environment:
      PMA_HOST: db  # Tells phpMyAdmin to connect to the service named 'mariadb'
    depends_on:
      - db
    ports:
      - "8091:80"  
    networks:
      - app-network

volumes:
  db_data:

networks:
  webnet-ldap:
    external: true 
  app-network:
    external: true 