services:
  db:
    image: mariadb:latest
    container_name: gestio-db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}  
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb:/var/lib/mysql
    networks:
      - webnet-gestio

  gestio:
    image: captwhite/gestio:latest
    container_name: gestio-app
    restart: always
    env_file:
      - ./.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gestio-http.entrypoints=web"
      - "traefik.http.routers.gestio-http.rule=Host(`gestio.captwhite.com`)"
      - "traefik.http.routers.gestio-http.middlewares=redirect-to-https@docker"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      #
      - "traefik.http.routers.gestio.entrypoints=websecure"
      - "traefik.http.routers.gestio.rule=Host(`gestio.captwhite.com`)"
      - "traefik.http.routers.gestio.tls=true"
      - "traefik.http.routers.gestio.tls.certresolver=myresolver"
      - "traefik.http.services.gestio.loadbalancer.server.port=3000"
    networks:
      - webnet-gestio



  phpmyadmin:
    image: phpmyadmin
    container_name: gestio-phpmyadmin
    restart: unless-stopped
    init: true
    depends_on:
      - db
    networks:
      - webnet-gestio
    environment:
      - PMA_ARBITRARY=1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gestiodb-http.entrypoints=web"
      - "traefik.http.routers.gestiodb-http.rule=Host(`gestiodb.captwhite.com`)"
      - "traefik.http.routers.gestiodb-http.middlewares=redirect-to-https@docker"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      #
      - "traefik.http.routers.gestiodb.entrypoints=websecure"
      - "traefik.http.routers.gestiodb.rule=Host(`gestiodb.captwhite.com`)"
      - "traefik.http.routers.gestiodb.tls=true"
      - "traefik.http.routers.gestiodb.tls.certresolver=myresolver"
      - "traefik.http.services.gestiodb.loadbalancer.server.port=80"

networks:
  webnet-gestio:
    external: true